-- DB03
-- p25 ~ p27 12개 SELECT 쿼리

--#1
SELECT *
FROM T_STUDENT 
WHERE HEIGHT >= 180;

--#2
SELECT NAME , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT BETWEEN 60 AND 80;

--#3
SELECT *
FROM T_STUDENT 
WHERE DEPTNO1 IN (101, 201);

--#4
SELECT *
FROM  T_STUDENT 
WHERE NAME LIKE "김%";

--#5
SELECT NAME, GRADE, HEIGHT 
FROM T_STUDENT 
WHERE GRADE = 4 AND HEIGHT >= 170;

--#6
SELECT NAME, HEIGHT, GRADE , WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 1 OR WEIGHT >=80;

--#7
SELECT NAME , GRADE , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 2 AND HEIGHT > 180 AND WEIGHT > 70;

--#8
SELECT NAME , GRADE , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 2 AND (WEIGHT > 180 OR WEIGHT > 70);

--#9 t_emp 테이블에서 고용일(hiredate)가 1992년 이전인 사람들의 이름(ename) 과 고용일을 출력하세요
SELECT ENAME , HIREDATE 
FROM T_EMP 
WHERE HIREDATE < '1992-01-01';

--#10
SELECT NAME, BIRTHDAY , HEIGHT , WEIGHT
FROM T_STUDENT 
WHERE GRADE = 1
ORDER BY BIRTHDAY ASC;

--#11
SELECT NAME AS 이름, HEIGHT AS 키 
FROM T_STUDENT 
WHERE GRADE = 1
ORDER BY NAME ASC;

--#12  t_emp2 직원 테이블에서 생일(birthday) 이 1980년대생인 사람들의 이름과 생일만 출력하세요- 즉 (1980/01/01 ~ 1989/12/31 사이 출생한 직원들)
SELECT NAME , BIRTHDAY 
FROM T_EMP2 
WHERE  '1980-01-01' <= BIRTHDAY AND BIRTHDAY < '1990-01-01';

