-- 산술연산자
SELECT ENAME , SAL*1.1 -- 급여 10% 인상분
FROM T_EMP ;

SELECT ENAME , 
SAL , 
COMM , 
SAL + COMM
-- null 값과의 산술연산은 무조건 null! 
FROM T_EMP ;

--- WHERE 조건절
SELECT * 
FROM T_EMP 
WHERE JOB  = 'SALESMAN'; -- 대소문자 구문 필수


SELECT ENAME , SAL, DEPTNO 
FROM T_EMP 
WHERE DEPTNO = 10;

SELECT ENAME , SAL 
FROM T_EMP 
WHERE SAL >2000;

SELECT ENAME , EMPNO, SAL 
FROM T_EMP 
WHERE ENAME = 'SCOTT';

-- 연습
SELECT NAME, GRADE 
FROM T_STUDENT 
WHERE GRADE = 2 OR GRADE = 3;

SELECT NAME, GRADE 
FROM T_STUDENT 
WHERE GRADE IN (2, 3);

SELECT NAME, GRADE 
FROM T_STUDENT 
WHERE GRADE > 1 AND GRADE < 4;

SELECT NAME, GRADE 
FROM T_STUDENT 
WHERE GRADE NOT IN (1, 4);

SELECT NAME, GRADE 
FROM T_STUDENT 
WHERE GRADE BETWEEN 2 AND 3;

SELECT NAME , PAY , "POSITION" 
FROM T_PROFESSOR 
WHERE pay > 300 AND "POSITION" = '정교수'

SELECT NAME , "POSITION" 
FROM  T_PROFESSOR 
WHERE BONUS IS NULL;

SELECT NAME 
FROM T_PROFESSOR
WHERE NAME LIKE '김%';

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%NE%';

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '_A%';

-------------------------------------
---ORDER BY
SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%L%'
ORDER BY ENAME DESC;


SELECT ENAME , JOB , SAL 
FROM T_EMP 
ORDER BY JOB DESC, SAL ASC ;

SELECT NAME , GRADE , HEIGHT 
FROM T_STUDENT 
ORDER BY GRADE ASC , HEIGHT DESC;



CREATE TABLE phonebook_T(
    id NUMBER CONSTRAINT PHT_ID_PK PRIMARY KEY,
    name VARCHAR2(50) CONSTRAINT PHT_NAME_NN NOT NULL,
    phone VARCHAR2(100) CONSTRAINT PHT_PHONE_UK UNIQUE,
    email VARCHAR2(100),
    age NUMBER 
    DEFAULT 21 
    CONSTRAINT PHT_AGE_CK CHECK(AGE>20),
    memo CLOB,
    regdate DATE,
    DEPTNO VARCHAR2(6) CONSTRAINT PHT_DEPTNO_FK REFERENCES T_DEPT2(DCODE) ON DELETE CASCADE
);

SELECT * FROM PHONEBOOK_T;

INSERT INTO PHONEBOOK_T(ID, NAME, PHONE, MEMO) VALUES (2, '오형돈', '011-1111-2222', 'jff@test.com');

UPDATE PHONEBOOK_T SET ID = 7 WHERE NAME = '오형돈';

DELETE PHONEBOOK_T WHERE NAME = '오형돈';



