SELECT *
FROM T_PROFESSOR ;

SELECT COUNT(*), COUNT(HPAGE) 
FROM  T_PROFESSOR ; -- 그룹함수에서는 NULL 값은 계산에서 제외

SELECT COUNT(BONUS), SUM(BONUS), AVG(BONUS)
FROM T_PROFESSOR ; -- 보너스 받는 사람의 평균임

SELECT MAX(HIREDATE ), MIN(HIREDATE ) 
FROM T_PROFESSOR ;

---NULL 허용 컬럼의 그룹함수 적용시
-- NVL, NVL2 하용해야 함

SELECT AVG(BONUS ), AVG(NVL(BONUS ,0)) 
FROM T_PROFESSOR ;

-- 학과별 평균
-- 불가능하다! SELECT 절에 GROUP 함수와 GROUP 함수가 아닌 것과는 같이 출력 불가
--SELECT DEPTNO, AVG(BONUS) 
--FROM T_PROFESSOR 


SELECT DEPTNO, ROUND(AVG(NVL(BONUS,0)),1) 보너스평균
FROM T_PROFESSOR
GROUP BY DEPTNO ;

--#5101
SELECT  DEPTNO , "POSITION" ,AVG(PAY) 평균급여
FROM T_PROFESSOR 
GROUP BY DEPTNO , "POSITION"  --별명 사용 불가 1.학과별 그룹핑, 2. 직급별 그룹핑
ORDER BY DEPTNO ASC, "POSITION" ASC ;

-- HAVING : 그룹함수 결과에 대한 조건절
SELECT DEPTNO , AVG(PAY ) 평균급여
FROM T_PROFESSOR 
--WHERE AVG(PAY) > 450 --그룹 함수는 WHERE 절에서 사용 불가
GROUP BY DEPTNO
HAVING AVG(PAY) > 450;

--<SELECT 쿼리문 순서>

--SELECT
--FROM
--WHERE
--GROUP BY
--HAVING
--ORDER BY

SELECT *
FROM T_EMP 

--#5102
SELECT MGR 매니저, COUNT(ENAME) 직원수, SUM(SAL) 급여총액, trunc(AVG(SAL)) 급여평균, AVG(NVL(COMM,0)) 교통비평균
FROM T_EMP 
WHERE MGR IS NOT NULL -- job <> 'PRESIDENT'
GROUP BY MGR;

--#5103
SELECT DEPTNO , 
COUNT(NAME) 총인원, ROUND(AVG(SYSDATE -HIREDATE),1) 근속평균, AVG(PAY) 급여평균, AVG(NVL(BONUS ,0)) 보너스  
FROM T_PROFESSOR 
WHERE "POSITION" = '정교수' OR "POSITION" = '조교수' -- POSITION LIKE'%교수'
GROUP BY DEPTNO ;


--#5104
SELECT DEPTNO1 학과, MAX(WEIGHT)-MIN(WEIGHT) 최대최소몸무게차
FROM T_STUDENT 
GROUP BY DEPTNO1 ;


--#5105
SELECT DEPTNO1 학과, MAX(WEIGHT)-MIN(WEIGHT) 최대최소몸무게차
FROM T_STUDENT 
GROUP BY DEPTNO1 
HAVING MAX(WEIGHT)-MIN(WEIGHT) >= 30;

 