
INSERT INTO T_STUDENT VALUES (9091, '김수진', 'soopuls', 101, 2, 1004);

COMMIT;

SELECT *
FROM T_STUDENT ;

DELETE FROM T_STUDENT WHERE GRADE = 4;

COMMIT;

SELECT NAME 이름, PAY 급여 
FROM T_PROFESSOR
WHERE PAY >= 5000;

CREATE INDEX idx_student_name ON T_STUDENT(NAME);

SELECT NAME , PROFNO 
FROM T_PROFESSOR 


SELECT p.NAME "교수님 이름", d.DNAME "소속 학과명" 
FROM T_PROFESSOR p, T_DEPARTMENT d 
WHERE p.DEPTNO = d.DEPTNO ;


SELECT p.NAME "교수님 이름", d.DNAME "소속 학과명" 
FROM T_PROFESSOR p, T_DEPARTMENT d 
WHERE p.PRONFO = d.PROFNO ;

SELECT NAME ,DEPTNO1 
FROM T_STUDENT
WHERE DEPTNO1 = (SELECT DEPTNO, DNAME FROM T_DEPARTMENT); 


SELECT DEPTNO, DNAME 
FROM T_DEPARTMENT 

SELECT s.NAME "학생이름", d.DNAME "학과명" 
FROM T_STUDENT s JOIN T_DEPARTMENT d ON s.DEPTNO1 =d.DEPTNO 
WHERE s.DEPTNO1  =(SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나');

SELECT s.NAME "학생이름" , d.DNAME "학과명" 
FROM T_STUDENT s JOIN T_DEPARTMENT d ON s.DEPTNO =d.DEPTNO 
WHERE s.DEPTNO  =(SELECT DEPTNO FROM T_STUDENT WHERE NAME = '이윤나');


CREATE OR REPLACE VIEW v_stud_info
AS
SELECT s.NAME , d.DNAME , p.NAME 
FROM T_STUDENT s, T_DEPARTMENT d,  T_PROFESSOR p
WHERE s.DEPTNO1 = d.DEPTNO  AND s.PROFNO = p.PROFNO ;

SELECT s.NAME , d.DNAME 
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO

CREATE OR REPLACE VIEW v_stud_info
AS
SELECT t.NAME , t.DNAME , p.NAME 
FROM (SELECT s.NAME , d.DNAME, s.PROFNO 
FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO
) t,  T_PROFESSOR p
WHERE  t.PROFNO = t.PROFNO ;


ALTER TABLE T_STUDENT ADD (BIRTHDAY DATE);


CREATE TABLE T_MEMBER (
	mb_uid NUMBER CONSTRAINT MEMBER_UID_PK PRIMARY KEY,
	mb_name VARCHAR2(20) CONSTRAINT MEMBER_NAME_NN NOT NULL,
	mb_jumin VARCHAR2(13) CONSTRAINT MEMBER_JUMIN_UK UNIQUE,
	mb_age NUMBER CONSTRAINT MEMBER_AGE_CK CHECK(mb_age > 0),
	mb_dept NUMBER CONSTRAINT MEMBER_DEPT_FK REFERENCES T_DEPT(DCODE)
);


SELECT s.NAME 학생이름, e.TOTAL 점수, c.GRADE 학점 
FROM T_EXAM01 e JOIN T_STUDENT s ON s.STUDNO = e.STUDNO 
				JOIN T_CREDIT c ON e.TOTAL BETWEEN c.MIN_POINT AND c.MAX_POINT 
ORDER BY e.TOTAL DESC 
;

CREATE OR REPLACE VIEW v_stud_info(학생이름, 학생학과명, "담당교수님 이름")
AS
SELECT s.NAME , d.DNAME , p.NAME 
FROM T_STUDENT s JOIN T_DEPARTMENT d ON s.DEPTNO1 = d.DEPTNO 
				JOIN T_PROFESSOR p ON s.PROFNO = p.PROFNO;
			

CREATE OR REPLACE VIEW v_stud_info(sname, dname, pname)
AS
SELECT s.NAME , d.DNAME , p.NAME 
FROM T_STUDENT s JOIN T_DEPARTMENT d ON s.DEPTNO = d.DEPTNO 
				JOIN T_PROFESSOR p ON s.PROFNO = p.PROFNO;
