CREATE OR REPLACE VIEW V_PROF 
AS 
SELECT PROFNO, NAME, EMAIL, HPAGE
FROM T_PROFESSOR 
;
-- name is already used by an existing object

SELECT *
FROM V_PROF;

SELECT TNAME FROM TAB; --VIEW 확인 가능


-- VIEW 생성시 별도의 컬럼이름을 지정해줄 수 있다
CREATE OR REPLACE VIEW V_PROF(PFNO, NM, EM, HP)
AS 
SELECT PROFNO, NAME, EMAIL, HPAGE
FROM T_PROFESSOR 
;

SELECT * FROM V_PROF;


--#8102
CREATE OR REPLACE VIEW V_PROF_DEPT(교수번호, 교수명, 소속학과명)
AS
SELECT p.PROFNO , p.NAME , d.DNAME 
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO  = d.DEPTNO 
;

SELECT * FROM V_PROF_DEPT;


SELECT DEPTNO1 , MAX(HEIGHT ) MAX_HEIGHT, MAX(WEIGHT ) MAX_WEIGHT
FROM T_STUDENT 
GROUP BY DEPTNO1


SELECT d.DNAME 학과명, s.MAX_HEIGHT, s.MAX_WEIGHT
FROM 
(SELECT DEPTNO1 , MAX(HEIGHT ) MAX_HEIGHT, MAX(WEIGHT ) MAX_WEIGHT
FROM T_STUDENT 
GROUP BY DEPTNO1 ) s,
T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO ;
--8104
SELECT d.DNAME 학과명, a.MAX_HEIGHT 최대키, s.NAME , s.HEIGHT 
FROM 
(SELECT DEPTNO1, MAX(HEIGHT ) MAX_HEIGHT
FROM T_STUDENT
GROUP BY DEPTNO1 ) a,
T_STUDENT s,
T_DEPARTMENT d
WHERE  s.DEPTNO1  = a.DEPTNO1 AND s.HEIGHT = a.MAX_HEIGHT AND s.DEPTNO1  = d.DEPTNO 


--8105

SELECT s.GRADE , s.NAME , s.HEIGHT,  a.AVG_HEIGHT
FROM 
(SELECT GRADE , AVG(HEIGHT ) AVG_HEIGHT
FROM T_STUDENT 
GROUP BY GRADE ) a,
T_STUDENT s
WHERE a.GRADE = s.GRADE AND s.HEIGHT > a.AVG_HEIGHT
ORDER BY 1;



