-- 다중칼럼 SUB QUERY
-- #7201

SELECT GRADE , MAX(HEIGHT) FROM T_STUDENT GROUP BY GRADE ;

SELECT GRADE 학년, NAME 이름, HEIGHT 키
FROM T_STUDENT 
WHERE (GRADE , HEIGHT ) IN ( SELECT GRADE , MAX(HEIGHT) FROM T_STUDENT GROUP BY GRADE )
ORDER BY 학년 ASC; -- ORDER BY는 SELECT 다음 수행되므로 별명 사용 가능
;

--#7202

SELECT DEPTNO , TO_CHAR(MIN(HIREDATE ), 'YYYY-MM-DD') FROM T_PROFESSOR GROUP BY DEPTNO 

SELECT p.PROFNO , p.NAME , p.HIREDATE ,d.DNAME 
FROM T_PROFESSOR p, T_DEPARTMENT d 
WHERE p.DEPTNO = d.DEPTNO 
AND (p.DEPTNO , TO_CHAR(p.HIREDATE,'YYYY-MM-DD')) IN (SELECT DEPTNO , TO_CHAR(MIN(HIREDATE ), 'YYYY-MM-DD') FROM T_PROFESSOR GROUP BY DEPTNO )
ORDER  BY 4

--#7203

SELECT POST , MAX(PAY) FROM T_EMP2 GROUP BY POST

SELECT NAME , POST , PAY 
FROM T_EMP2 
WHERE (POST, PAY) IN (SELECT POST , MAX(PAY) FROM T_EMP2 GROUP BY POST )
ORDER BY PAY;

-- #7204

SELECT d.DNAME , AVG(e.PAY ) FROM T_EMP2 e, T_DEPT2 d WHERE e.DEPTNO = d.DCODE GROUP BY d.DNAME ;

SELECT d.DNAME 부서명, e.NAME 직원명, e.PAY 연봉 
FROM T_EMP2 e, T_DEPT2 d
WHERE  e.DEPTNO = d.DCODE 
AND e.PAY < ALL(SELECT AVG(e.PAY ) FROM T_EMP2 e, T_DEPT2 d WHERE e.DEPTNO = d.DCODE GROUP BY d.DNAME )
ORDER BY 3;

SELECT AVG(PAY ) FROM T_EMP2 GROUP BY DEPTNO ;

SELECT d.DNAME 부서명, e.NAME 직원명, e.PAY 연봉 
FROM T_EMP2 e, T_DEPT2 d
WHERE  e.DEPTNO = d.DCODE 
AND e.PAY < ALL(SELECT AVG(PAY ) FROM T_EMP2 GROUP BY DEPTNO )
ORDER BY 3;

--#7205
SELECT a.NAME 사원이름, NVL(a.POST, ' ') 직급, a.PAY 급여
FROM T_EMP2 a
WHERE a.PAY >= (SELECT AVG(b.PAY) FROM T_EMP2 b WHERE NVL(a.POST, ' ') = NVL(b.POST, ' '))
;

SELECT AVG(b.PAY) FROM T_EMP2 b WHERE '과장' = b.POST;

--#7206
SELECT NAME 사원이름, 
(SELECT d.DNAME FROM T_DEPT2 d WHERE e.DEPTNO  = d.DCODE) 부서이름
FROM T_EMP2 e;







