SELECT *
FROM  T_EMP;

SELECT SAL FROM T_EMP  WHERE ENAME  = 'SCOTT';

-- #7101
SELECT ENAME , SAL 
FROM T_EMP 
WHERE SAL > (SELECT SAL FROM T_EMP  WHERE ENAME  = 'SCOTT')

--#7102
SELECT MAX(HEIGHT ) 
FROM T_STUDENT;

SELECT NAME , HEIGHT 
FROM  T_STUDENT 
WHERE HEIGHT = (SELECT MAX(HEIGHT ) FROM T_STUDENT);

--1.단일행 서브 쿼리
--#7103
SELECT DEPTNO1 FROM T_STUDENT  WHERE NAME = '이윤나';

SELECT s.NAME , d.DNAME 
FROM T_STUDENT s JOIN T_DEPARTMENT d ON s.DEPTNO1 =d.DEPTNO 
WHERE s.DEPTNO1  =(SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나');

-- #7104
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME  = '송도권';

SELECT p.NAME 교수명, TO_CHAR(p.HIREDATE, 'YYYY-MM-DD') 입사일 , d.DNAME 학과명
FROM T_PROFESSOR p JOIN T_DEPARTMENT d ON p.DEPTNO  = d.DEPTNO
WHERE p.HIREDATE > (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME  = '송도권');

-- #7105
(SELECT AVG(WEIGHT ) FROM T_STUDENT WHERE DEPTNO1 = 101)

SELECT NAME , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT >(SELECT AVG(WEIGHT ) FROM T_STUDENT WHERE DEPTNO1 = 101);

--#7106
SELECT HIREDATE FROM T_PROFESSOR WHERE NAME ='심슨'

SELECT PAY FROM T_PROFESSOR WHERE NAME ='조인형'

SELECT NAME , PAY , TO_CHAR(HIREDATE )
FROM T_PROFESSOR
WHERE TO_CHAR(HIREDATE, 'YYYY-MM-DD') = TO_CHAR((SELECT HIREDATE FROM T_PROFESSOR WHERE NAME ='심슨'), 'YYYY-MM-DD')
AND PAY < (SELECT PAY FROM T_PROFESSOR WHERE NAME ='조인형');

SELECT EMPNO , NAME , DEPTNO 
FROM T_EMP2 
WHERE DEPTNO IN (SELECT DCODE FROM T_DEPT2 WHERE AREA ='서울지사');
-- SQL Error [1427] [21000]: ORA-01427: single-row subquery returns more than one row


--#7108
SELECT NAME , POST , TO_CHAR(PAY, '999,999,999')||'원' 연봉 
FROM T_EMP2 
WHERE PAY > ANY(SELECT PAY FROM T_EMP2 WHERE POST = '과장');

SELECT PAY FROM T_EMP2 WHERE POST = '과장'

--#7109
SELECT NAME 이름, GRADE 학년, WEIGHT 몸무게 
FROM T_STUDENT 
WHERE WEIGHT < ALL(SELECT WEIGHT FROM T_STUDENT WHERE GRADE ='4')

SELECT WEIGHT FROM T_STUDENT WHERE GRADE ='4'


