-- CONSTRAINT
-- 테이블 생성시 동시에 설정하기

-- DCODE 참조예정
SELECT * FROM T_DEPT2 ; -- DCODE: 0001, 1000 .... 1011

--#9001
-- 제약조건명을 명시하지 않는 방법

DROP TABLE T_EMP3 CASCADE CONSTRAINT ;

CREATE TABLE T_EMP3 (
	NO NUMBER(4) PRIMARY KEY,
	NAME VARCHAR2(10) NOT NULL,
	JUMIN VARCHAR2(13) NOT NULL UNIQUE,
	AREA NUMBER(1) CHECK(AREA <5),
	DEPTNO VARCHAR2(6) REFERENCES T_DEPT2(DCODE)
);

-- 별도의 항목으로 제약조건 정의 가능
DROP TABLE T_EMP4 CASCADE CONSTRAINT ;

CREATE TABLE T_EMP4 (
	NO NUMBER(4) ,
	NAME VARCHAR2(10) NOT NULL, --NOT NULL 은 별도 정의 안 됨.
	JUMIN VARCHAR2(13) NOT NULL ,
	AREA NUMBER(1) ,
	DEPTNO VARCHAR2(6),
	PRIMARY KEY(NO),
	UNIQUE(JUMIN),
	CHECK(AREA < 5),
	FOREIGN KEY(DEPTNO) REFERENCES T_DEPT2(DCODE)
);


--#9002
--제약조건명을 명시하여 정의

DROP TABLE T_EMP3 CASCADE CONSTRAINT ;

CREATE TABLE T_EMP3 (
	NO NUMBER(4) CONSTRAINT EMP3_NO_PK PRIMARY KEY,
	NAME VARCHAR2(10) CONSTRAINT EMP3_NAME_NN NOT NULL,
	JUMIN VARCHAR2(13) 
		CONSTRAINT EMP3_JUMIN_NN NOT NULL 
		CONSTRAINT EMP3_JUMIN_UK UNIQUE,
	AREA NUMBER(1) CONSTRAINT EMP3_AREA_CK CHECK(AREA <5),
	DEPTNO VARCHAR2(6) CONSTRAINT EMP3_DEPTNO_FK REFERENCES T_DEPT2(DCODE)
);



DROP TABLE T_EMP3 CASCADE CONSTRAINT ;

CREATE TABLE T_EMP3 (
	NO NUMBER(4),
	NAME VARCHAR2(10) CONSTRAINT EMP3_NAME_NN NOT NULL,
	JUMIN VARCHAR2(13) CONSTRAINT EMP3_JUMIN_NN NOT NULL,
	AREA NUMBER(1),
	DEPTNO VARCHAR2(6),
	CONSTRAINT EMP3_NO_PK PRIMARY KEY(NO),
	CONSTRAINT EMP3_JUMIN_UK UNIQUE(JUMIN),
	CONSTRAINT EMP3_AREA_CK CHECK(AREA<5),
	CONSTRAINT EMP3_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES T_DEPT2(DCODE)
);

-- #9003 제약조건 조회하기
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE , STATUS 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_EMP4'; -- 테이블명 대문자로!

SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE , STATUS 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_EMP3'; -- 테이블명 대문자로!


--#9005

INSERT INTO T_EMP3 VALUES(1,'오라클', '1234561234567', 4, 1000);
--2번 실행하면 오류: SQL Error [1] [23000]: ORA-00001: unique constraint (SCOTT0316.EMP3_NO_PK) violated

INSERT INTO T_EMP3 VALUES(2,'오라클', '1234561234567', 4, 1000);
--JUMIN UNIQUE 오류: SQL Error [1] [23000]: ORA-00001: unique constraint (SCOTT0316.EMP3_JUMIN_UK) violated

INSERT INTO T_EMP3 VALUES(2,'오라클', '2222222222222222', 4, 1000);
-- SQL Error [12899] [72000]: ORA-12899: value too large for column "SCOTT0316"."T_EMP3"."JUMIN" (actual: 16, maximum: 13)

INSERT INTO T_EMP3 VALUES(3,'오라클', '2222222222222', 10, 1000);
-- SQL Error [1438] [22003]: ORA-01438: value larger than specified precision allowed for this column

INSERT INTO T_EMP3 VALUES(3,'오라클', '2222222222222', 3, 2000);
-- SQL Error [2291] [23000]: ORA-02291: integrity constraint (SCOTT0316.EMP3_DEPTNO_FK) violated - parent key not found

INSERT INTO T_EMP3 (NO, JUMIN, AREA, DEPTNO) VALUES (2, '3333333333333', 4, 1001);
-- SQL Error [1400] [23000]: ORA-01400: cannot insert NULL into ("SCOTT0316"."T_EMP3"."NAME")

-- INSERT 뿐 아니라 UPDATE/DELETE 에서도 오류 발생 가능
UPDATE T_EMP3 SET AREA = 10 WHERE NO=1;
-- SQL Error [1438] [22003]: ORA-01438: value larger than specified precision allowed for this column

DELETE FROM T_DEPT2 WHERE DCODE = 1000; -- 참조하고 있는 부모는 삭제 불가
-- SQL Error [2292] [23000]: ORA-02292: integrity constraint (SCOTT0316.EMP3_DEPTNO_FK) violated - child record found

--#9005 테이블 생성 후에 ALTER 명령 사용하여 제약조건 추가 가능!
--T_EMP4에 NAME 컬럼 UNIQUE 제약 조건 추가
--ALTER TABLE ~ ADD
--ALTER TABLE ~ MODIFY
--ALTER TABLE ~ DROP 


ALTER TABLE T_EMP4 ADD CONSTRAINT EMP4_NAME_UK UNIQUE(NAME);

--#9006
-- T_EMP4 테이블의 AREA 컴럼에 NOT NULL 체약 조건 추가해보세요
ALTER TABLE T_EMP4 ADD CONSTRAINT EMP4_AREA_NN NOT NULL;
-- 이미 컬럼의 기본값인 NULL로 되어 있기 때문에 ADD가 아닌 MODIFY로 해야 한다.

ALTER TABLE T_EMP4 MODIFY(AREA CONSTRAINT EMP4_ARE_NN NOT NULL);

--#9007
ALTER TABLE T_EMP4 ADD CONSTRAINT EMP4_NAME_FK FOREIGN KEY(NAME) REFERENCES T_EMP2(NAME);
-- SQL Error [2270] [42000]: ORA-02270: no matching unique or primary key for this column-list
-- 참조되는 부모 테이블의 컬럼은 PRIMARY KEY이거나 UNIQUE해야 한다.

-- 일단 부모 테이블의 NAME을 UNIQUE로 바꾼 뒤 위  쿼리를 다시 실행 
ALTER TABLE T_EMP4 ADD CONSTRAINT EMP2_NAME_FK UNIQUE(NAME);

SELECT *
FROM USER_CONSTRAINTS



--#9008

DROP TABLE T_EMP3 CASCADE CONSTRAINT ;

CREATE TABLE T_EMP3 (
	NO NUMBER(4) CONSTRAINT EMP3_NO_PK PRIMARY KEY,
	NAME VARCHAR2(10) CONSTRAINT EMP3_NAME_NN NOT NULL,
	JUMIN VARCHAR2(13) 
		CONSTRAINT EMP3_JUMIN_NN NOT NULL 
		CONSTRAINT EMP3_JUMIN_UK UNIQUE,
	AREA NUMBER(1) CONSTRAINT EMP3_AREA_CK CHECK(AREA <5),
	DEPTNO VARCHAR2(6) 
		CONSTRAINT EMP3_DEPTNO_FK REFERENCES T_DEPT2(DCODE)
		ON DELETE CASCADE --부모 삭제되면 자식도 같이 삭제
		--ON DELETE SET  NULL --부모 삭제되면 NULL 값으로
);

--#9009
--부모 테이블이 삭제되면 NULL이 되도록 설정(ALTER 사용)
ALTER TABLE T_EMP4 DROP CONSTRAINT EMP4_NAME_FK;

ALTER TABLE T_EMP4 ADD CONSTRAINT EMP4_NAME_FK FOREIGN KEY(NAME) REFERENCES T_EMP2(NAME) ON DELETE SET NULL;


---- DISABLE NOVALIDATE

SELECT * FROM T_NOVALIDATE; 
SELECT * FROM T_VALIDATE ;

SELECT OWNER, CONSTRAINT_NAME , CONSTRAINT_TYPE , STATUS 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME  = 'T_VALIDATE';

SELECT OWNER, CONSTRAINT_NAME , CONSTRAINT_TYPE , STATUS 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME  = 'T_NOVALIDATE';


INSERT INTO T_VALIDATE VALUES(1,'DDD'); --- 처음에는 에러! PK니까

INSERT INTO T_NOVALIDATE VALUES(1,'DDD'); --- 처음에는 에러! PK니까

ALTER TABLE T_NOVALIDATE DISABLE NOVALIDATE CONSTRAINT SYS_C007033;

ALTER TABLE T_NOVALIDATE ENABLE NOVALIDATE CONSTRAINT SYS_C007033;
--SQL Error [2437] [72000]: ORA-02437: cannot validate (SCOTT0316.SYS_C007033) - primary key violated

DELETE FROM T_NOVALIDATE WHERE NAME = 'DDD';
